services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: >
      sh -c "[ ! -f .env ] && cp .env.example .env || true &&
             php artisan key:generate &&
             touch /var/www/database/database.sqlite &&
             php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

